### ISSUE TITLE
Mongo is not supported

### ISSUE THREAD

**Issue by soysauce5G** [pyeventsourcing/eventsourcing#212]
The eventsourcing module is not supporting mongo. Mongo is one of the most popular database for non-relational database. With the mongo support this module would gain a lot more attention.

**Comment by johnbywater** [comment]
Thanks for your interest. How would it work with Mongo?

For the library's SimpleApplication class (which has a repository and a notification log) we need atomically to write contiguous sequences for the domain events of aggregates and for event notifications in of the application

For the ProcessApplication class (which extends the SimpleApplication class by processing event from other applications) we need atomically to write tracking records along with the domain events and the event notifications.

Perhaps it would work to write "process event" documents with the three factors (domain events, event notifications, tracking) as embedded documents?

I don't really understand Mongo intimately... Would that allow the included domain events to be retrieved efficiently when an aggregate is accessed, and separately for the event notifications to be retrieved when a notification log is accessed, and also separately for position in upstream sequence to be accessed?

Perhaps we could create a prototype and see whether this is feasible?

**Comment by soysauce5G** [comment]
Cool, will start investigate the possibility of creating one, in the meantime will close the issue.

**Comment by paulito-bandito** [comment]
Hi all, did that mongo integration prototype get built? Curious if it were available to look at.

**Comment by johnbywater** [comment]
> Would it be possible to prevent conflicts in the writing of aggregate events so that only one event is stored for each version of the aggregate (optimistic concurrent control)? Would it be possible to generate a monotonically increasing sequence of event notification IDs? Would it be possible for the domain events of an aggregate to be retrieved efficiently when an aggregate is accessed (secondary indexes)? If these things are possible with MongoDB, we can probably adapt it.

Just been looking at the sequence generation support in MongoDB. It seems that it doesn't really support what we would need. So I guess it would be possible to build an event store server using MongoDB, but not really use it directly as an event store? I'm not sure about this, but if it can support the above requirements, then I would be happy to help make this happen.

In the meantime, I will close this issue again, since some time has gone by and nothing has happened.
