### ISSUE TITLE
Postgres schema change possibility

### ISSUE THREAD

**Issue by marcinmigda-talentalpha** [pyeventsourcing/eventsourcing#237]
It would be nice to be able to choose a schema other than the default one for Postgres eventstore. Are you planning to add support for it?

**Comment by johnbywater** [comment]
Hi @marcinmigda-talentalpha! Thanks for your question, sorry for the delay in responding. There aren't currently any plans to do this, but I'm open to the idea. I suppose the limitation is that the SQL in the recorders depends on the schema. How would you like support for an alternative schema to work? Did you want something in particular from an alternative scheme? Is there something you would like to do that you currently can't? Just curious about your thoughts, experience, and requirements. Hope to hear more about this from you soon!

**Comment by teves-castro** [comment]
I'm still quite new to using this library so I'm still learning the entry points for its functionality, but that being said having an environment variable seems like a reasonable choice to indicate which Schema the tables should be created in.

**Comment by johnbywater** [comment]
@marcinmigda-talentalpha @teves-castro

I added this today. Thanks for raising and explaining. Sorry for delay. Let me know what you think?

"The optional environment variable POSTGRES_SCHEMA may be used to configure the table names used by the recorders to be qualified with a schema name. Setting this will create tables in a specific PostgreSQL schema. See the PostgreSQL Schemas documentation for more information about creating and using PostgreSQL schemas safely."

See docs:
https://eventsourcing.readthedocs.io/en/latest/topics/persistence.html#postgresql

Changeset:
https://github.com/pyeventsourcing/eventsourcing/commit/0967e025ca819335e7b154320c841bc6041cad18
