### ISSUE TITLE
monotonic 

### ISSUE THREAD

**Issue by austinnichols101** [pyeventsourcing/eventsourcing#249]
`time.time()` returns a float (time in seconds since `epoch`).
`time.monotonic()` returns a float (a clock that never goes backwards) 

```
datetime.fromtimestamp(monotonic(), timezone.utc)
```
will always generate *1970-01-02 19:19:18:508179+00:00* because the monotonic value is < epoch

_"The epoch is the point where the time starts, and is platform dependent. For Unix, the epoch is January 1, 1970, 00:00:00 (UTC). To find out what the epoch is on a given platform, look at time.gmtime(0)."_

![image](https://user-images.githubusercontent.com/6962379/163687673-38d63cbf-5434-4b02-a6de-ded36a2ad839.png)

**Comment by johnbywater** [comment]
Thanks for noticing this. I will fix it now.

**Comment by johnbywater** [comment]
Just released version 9.2.5, which fixes this.

https://pypi.org/project/eventsourcing/9.2.5/

 Thanks again for noticing this and raising the issue!
