### ISSUE TITLE
support postgresql as alias for postgres persistence module

### ISSUE THREAD

**Issue by elmanm** [pyeventsourcing/eventsourcing#252]
Can we add support for `eventsourcing.postgresql` as a PERSISTENCE_MODULE` value?

e.g. add a file `postgresql.py` with just `from postgres import *` in it?

**Comment by johnbywater** [comment]
Yes it's possible. But may I ask why you would like this? what's the benefit? what's the issue with the current module name? what motivated this? I'm just curious :)

**Comment by elmanm** [comment]
Where I load my database configuration from happens to use the full `postgresql` name for the drivername, and it will would be really convenient not to have to map `postgresql` -> `postgres` so that I can use it dynamically. 

Basically, it would be a small convenience improvement for when using other technologies that only support the full name.

**Comment by johnbywater** [comment]
I understand, thank you for explaining. I feel it's probably better for you to code an explicit mapping, and that way you can also code a nice error in case you are using a driver name that doesn't happen to coincide with an actually existing persistence module?
